spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

hu:
  virgo:
    calendar:
      event-start-time: 09:00:00Z
      event-end-time: 17:00:00Z
      event-min-length: 30
      event-max-length: 180
      event-start-minutes:
          - 0
          - 30
      time-slot-size: 30

      first-day-of-week: 'MONDAY'
      unavailable-days:
        - 'SUNDAY'
        - 'SATURDAY'